---
- name: Add authorized_keys for users
  authorized_key:
    user: "{{ item.0.user }}"
    state: present
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ openssh_authorized_keys }}"
    - keys
  when: openssh_authorized_keys | length
